export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const SET_USER = 'SET_USER';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const SELECT_CATEGORIES = 'SELECT_CATEGORIES';
export const REMOVE_CATEGORIES = 'REMOVE_CATEGORIES';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const DELETE_CATEGORIES = 'DELETE_CATEGORIES';